exportTrainTimings = {
    "LWEB": {
        "AL": 14,
        "BU": 7,
        "AP": 6,
        "BO": 5,
        "OA": 7,
        "CL": 8,
        "PO": 7,
        "LO": 6,
        "MI": 7,
        "EX": 9,
        "UN": 12
    },
    "LEWB": {
        "WH": 6,
        "AJ": 8,
        "PIN": 6,
        "RO": 8,
        "GU": 7,
        "EG": 5,
        "SC": 5,
        "DA": 6,
        "UN": 17
    },
    "LWWB": {
        "EX": 8,
        "MI": 8,
        "LO": 6,
        "PO": 6,
        "CL": 7,
        "OA": 7,
        "BO": 6,
        "AP": 6,
        "BU": 6,
        "AL": 8,
        "WR": 14,
        "HA": 13
    },
    "LEEB": {
        "DA": 11,
        "SC": 6,
        "EG": 5,
        "GU": 5,
        "RO": 6,
        "PIN": 8,
        "AJ": 5,
        "WH": 7,
        "OS": 12
    }
}

exportBoardNumberings = {
    "LWEB": {
        "HA": 128,
        "WR": 124, 
        "AL": 120,
        "BU": 118,
        "AP": 115,
        "BO": 112,
        "OA": 109,
        "CL": 105,
        "PO": 102,
        "LO": 99,
        "MI": 96,
        "EX": 93,
        "UN": 91,
    },
    "LEEB": {
        "UN": 90,
        "DA": 86,
        "SC": 83,
        "EG": 81,
        "GU": 79,
        "RO": 76,
        "PIN": 73,
        "AJ": 71,
        "WH": 67,
        "OS": 65
    },
    "LEWB": {
        "OS": 64,
        "WH": 62,
        "AJ": 58,
        "PIN": 56,
        "RO": 53,
        "GU": 50,
        "EG": 48,
        "SC": 46,
        "DA": 43,
        "UN": 39,
    },
    "LWWB": {
        "UN": 38,
        "EX": 36,
        "MI": 33,
        "LO": 30,
        "PO": 27,
        "CL": 24,
        "OA": 20,
        "BO": 17,
        "AP": 14,
        "BU": 11,
        "AL": 9,
        "WR": 5,
        "HA": 1,
    }
}